version: '3'

services:
  redis-master:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - redisnet

  redis-slave1:
    image: redis
    command: redis-server --slaveof redis-master 6379
    networks:
      - redisnet

  redis-slave2:
    image: redis
    command: redis-server --slaveof redis-master 6379
    networks:
      - redisnet

networks:
  redisnet: